[#347] Setting framework 추가

diff --git a/.github/workflows/swift.yml b/.github/workflows/swift.yml
--- a/.github/workflows/swift.yml
+++ b/.github/workflows/swift.yml
@@ -97,6 +97,18 @@ jobs:
         env: 
           destination: ${{ matrix.destination }}
 
+      - name: Setting Scenes Unit Tests
+        id: test_setting_scenes
+        run: |
+          xcodebuild test \
+          -workspace Clean-Mooyaho-Codebase.xcworkspace \
+          -scheme SettingScene \
+          -destination "${destination}" \
+          -configuration Debug \
+          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty -c; echo "::set-output name=result::${PIPESTATUS[0]}"; echo "${PIPESTATUS[0]}"
+        env: 
+          destination: ${{ matrix.destination }}
+
       - name: Domain Unit Tests
         id: test_domain
         run: |
@@ -156,6 +168,11 @@ jobs:
 
       - name: Check Tests Viewer Scenes
         if: steps.test_viewer_scenes.outputs.result != 0
+        run: |
+          echo "Tests Failed"; exit 1
+
+      - name: Check Tests Setting Scenes
+        if: steps.test_setting_scenes.outputs.result != 0
         run: |
           echo "Tests Failed"; exit 1
       
