HoorayScene 추가

diff --git a/.github/workflows/swift.yml b/.github/workflows/swift.yml
--- a/.github/workflows/swift.yml
+++ b/.github/workflows/swift.yml
@@ -85,6 +85,18 @@ jobs:
         env: 
           destination: ${{ matrix.destination }}
 
+      - name: Hooray Scenes Unit Tests
+        id: test_hooray_scenes
+        run: |
+          xcodebuild clean test \
+          -workspace Clean-Mooyaho-Codebase.xcworkspace \
+          -scheme HoorayScene \
+          -destination "${destination}" \
+          -configuration Debug \
+          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
+        env: 
+          destination: ${{ matrix.destination }}
+
       - name: Domain Unit Tests
         id: test_domain
         run: |
@@ -139,6 +151,11 @@ jobs:
 
       - name: Check Tests Place Scenes
         if: steps.test_place_scenes.outputs.result != 0
+        run: |
+          echo "Tests Failed"; exit 1
+
+      - name: Check Tests Hooray Scenes
+        if: steps.test_hooray_scenes.outputs.result != 0
         run: |
           echo "Tests Failed"; exit 1
       
