카르타고 삭제 -> xcframework 임베드 하는 방식으로 변경
- admob만 앱타겟에서 빌드 -> admob 사용시 FirApp? 이 암묵적으로 GoogleService-info 앱번들에서 읽는듯 -> 테스트실패

diff --git a/.github/workflows/swift.yml b/.github/workflows/swift.yml
--- a/.github/workflows/swift.yml
+++ b/.github/workflows/swift.yml
@@ -33,7 +33,6 @@ jobs:
       #     restore-keys: |
       #       ${{ runner.os }}-spm-
 
-        
       - name: Domain Unit Tests
         id: test_domin
         run: |
@@ -59,17 +58,17 @@ jobs:
         env: 
           destination: ${{ matrix.destination }}
 
-      # - name: FirebaseService Unit Tests
-      #   id: test_fb
-      #   run: |
-      #     xcodebuild clean test \
-      #     -workspace BreadRoadCodeBase.xcworkspace \
-      #     -scheme FirebaseService \
-      #     -destination "${destination}" \
-      #     -configuration Debug \
-      #     CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
-      #   env: 
-      #     destination: ${{ matrix.destination }}
+      - name: FirebaseService Unit Tests
+        id: test_fb
+        run: |
+          xcodebuild clean test \
+          -workspace BreadRoadCodeBase.xcworkspace \
+          -scheme FirebaseService \
+          -destination "${destination}" \
+          -configuration Debug \
+          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
+        env: 
+          destination: ${{ matrix.destination }}
 
       - name: iOS App Unit Tests
         id: test_ios_app
@@ -93,10 +92,10 @@ jobs:
         run: |
           echo "Tests Failed"; exit 1
 
-      # - name: Check Tests FirebaseService
-      #   if: steps.test_fb.outputs.result != 0
-      #   run: |
-      #     echo "Tests Failed"; exit 1
+      - name: Check Tests FirebaseService
+        if: steps.test_fb.outputs.result != 0
+        run: |
+          echo "Tests Failed"; exit 1
           
       - name: Check Tests iOS App
         if: steps.test_ios_app.outputs.result != 0
